"""Initial migration

Revision ID: 4c255d31d3b2
Revises: 
Create Date: 2026-03-16 14:20:04.021874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c255d31d3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancer_incidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cancer_type', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('count', sa.Float(), nullable=True),
    sa.Column('asr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cancer_incidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cancer_incidence_cancer_type'), ['cancer_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_cancer_incidence_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancer_incidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cancer_incidence_year'))
        batch_op.drop_index(batch_op.f('ix_cancer_incidence_cancer_type'))

    op.drop_table('cancer_incidence')
    # ### end Alembic commands ###
